const data = {
  domain: "antoanthucpham.angiang.gov.vn",
  type: "Subdomain",
  discovery_reason: "Internal ASM",
  discovery_on: "2024-06-03 01:54:26",
  ip: "115.75.91.61",
  services: [
    {
      http: {
        request: {
          method: "GET",
          uri: "https://115.75.91.61",
        },
        response: {
          protocol: "HTTP/1.1",
          status_code: "200",
          status_reason: "OK",
          header_location: "",
          html_title: "",
        },
      },
      port: "21",
      service_name: "ftp",
      software: [
        {
          vendor: "ProFTPD or KnFTPD",
          product: "ProFTPD or KnFTPD",
          version: "",
        },
      ],
      vulnerabilities: [],
    },
    {
      http: {
        request: {
          method: "GET",
          uri: "https://115.75.91.61",
        },
        response: {
          protocol: "HTTP/1.1",
          status_code: "200",
          status_reason: "OK",
          header_location: "",
          html_title: "",
        },
      },
      port: "22",
      service_name: "ssh",
      software: [
        {
          vendor: "",
          product: "",
          version: "",
        },
      ],
      vulnerabilities: [],
    },
    {
      http: {
        request: {
          method: "GET",
          uri: "https://115.75.91.61",
        },
        response: {
          protocol: "HTTP/1.1",
          status_code: "200",
          status_reason: "OK",
          header_location: "",
          html_title: "",
        },
      },
      port: "25",
      service_name: "smtp",
      software: [
        {
          vendor: "Exim smtpd",
          product: "Exim smtpd",
          version: "4.90_1",
        },
      ],
      vulnerabilities: [],
    },
    {
      http: {
        request: {
          method: "GET",
          uri: "https://115.75.91.61",
        },
        response: {
          protocol: "HTTP/1.1",
          status_code: "200",
          status_reason: "OK",
          header_location: "",
          html_title: "",
        },
      },
      port: "53",
      service_name: "domain",
      software: [
        {
          vendor: "ISC BIND",
          product: "ISC BIND",
          version: "9.11.3-1ubuntu1.16",
        },
      ],
      vulnerabilities: [
        {
          id: "PRION:CVE-2021-25216",
          cvss: "6.8",
          type: "prion",
          is_exploit: "false",
          reference: "https://vulners.com/prion/PRION:CVE-2021-25216",
        },
        {
          id: "CVE-2021-25216",
          cvss: "6.8",
          type: "cve",
          is_exploit: "false",
          reference: "https://vulners.com/cve/CVE-2021-25216",
        },
        {
          id: "CVE-2020-8625",
          cvss: "6.8",
          type: "cve",
          is_exploit: "false",
          reference: "https://vulners.com/cve/CVE-2020-8625",
        },
        {
          id: "PRION:CVE-2020-8625",
          cvss: "5.1",
          type: "prion",
          is_exploit: "false",
          reference: "https://vulners.com/prion/PRION:CVE-2020-8625",
        },
        {
          id: "PRION:CVE-2021-25219",
          cvss: "5.0",
          type: "prion",
          is_exploit: "false",
          reference: "https://vulners.com/prion/PRION:CVE-2021-25219",
        },
        {
          id: "PRION:CVE-2021-25215",
          cvss: "5.0",
          type: "prion",
          is_exploit: "false",
          reference: "https://vulners.com/prion/PRION:CVE-2021-25215",
        },
        {
          id: "PRION:CVE-2020-8623",
          cvss: "5.0",
          type: "prion",
          is_exploit: "false",
          reference: "https://vulners.com/prion/PRION:CVE-2020-8623",
        },
        {
          id: "PRION:CVE-2020-8616",
          cvss: "5.0",
          type: "prion",
          is_exploit: "false",
          reference: "https://vulners.com/prion/PRION:CVE-2020-8616",
        },
        {
          id: "PRION:CVE-2019-6477",
          cvss: "5.0",
          type: "prion",
          is_exploit: "false",
          reference: "https://vulners.com/prion/PRION:CVE-2019-6477",
        },
        {
          id: "PRION:CVE-2018-5744",
          cvss: "5.0",
          type: "prion",
          is_exploit: "false",
          reference: "https://vulners.com/prion/PRION:CVE-2018-5744",
        },
        {
          id: "PRION:CVE-2018-5740",
          cvss: "5.0",
          type: "prion",
          is_exploit: "false",
          reference: "https://vulners.com/prion/PRION:CVE-2018-5740",
        },
        {
          id: "PACKETSTORM:157836",
          cvss: "5.0",
          type: "packetstorm",
          is_exploit: "true",
          reference: "https://vulners.com/packetstorm/PACKETSTORM:157836",
        },
        {
          id: "FBC03933-7A65-52F3-83F4-4B2253A490B6",
          cvss: "5.0",
          type: "githubexploit",
          is_exploit: "true",
          reference:
            "https://vulners.com/githubexploit/FBC03933-7A65-52F3-83F4-4B2253A490B6",
        },
        {
          id: "CVE-2023-2828",
          cvss: "5.0",
          type: "cve",
          is_exploit: "false",
          reference: "https://vulners.com/cve/CVE-2023-2828",
        },
        {
          id: "CVE-2022-38178",
          cvss: "5.0",
          type: "cve",
          is_exploit: "false",
          reference: "https://vulners.com/cve/CVE-2022-38178",
        },
        {
          id: "CVE-2022-38177",
          cvss: "5.0",
          type: "cve",
          is_exploit: "false",
          reference: "https://vulners.com/cve/CVE-2022-38177",
        },
        {
          id: "CVE-2022-2795",
          cvss: "5.0",
          type: "cve",
          is_exploit: "false",
          reference: "https://vulners.com/cve/CVE-2022-2795",
        },
        {
          id: "CVE-2021-25219",
          cvss: "5.0",
          type: "cve",
          is_exploit: "false",
          reference: "https://vulners.com/cve/CVE-2021-25219",
        },
        {
          id: "CVE-2021-25215",
          cvss: "5.0",
          type: "cve",
          is_exploit: "false",
          reference: "https://vulners.com/cve/CVE-2021-25215",
        },
        {
          id: "CVE-2020-8616",
          cvss: "5.0",
          type: "cve",
          is_exploit: "false",
          reference: "https://vulners.com/cve/CVE-2020-8616",
        },
        {
          id: "CVE-2019-6470",
          cvss: "5.0",
          type: "cve",
          is_exploit: "false",
          reference: "https://vulners.com/cve/CVE-2019-6470",
        },
        {
          id: "CVE-2018-5744",
          cvss: "5.0",
          type: "cve",
          is_exploit: "false",
          reference: "https://vulners.com/cve/CVE-2018-5744",
        },
        {
          id: "CVE-2018-5740",
          cvss: "5.0",
          type: "cve",
          is_exploit: "false",
          reference: "https://vulners.com/cve/CVE-2018-5740",
        },
        {
          id: "PRION:CVE-2019-6471",
          cvss: "4.3",
          type: "prion",
          is_exploit: "false",
          reference: "https://vulners.com/prion/PRION:CVE-2019-6471",
        },
        {
          id: "PRION:CVE-2019-6465",
          cvss: "4.3",
          type: "prion",
          is_exploit: "false",
          reference: "https://vulners.com/prion/PRION:CVE-2019-6465",
        },
        {
          id: "PRION:CVE-2018-5743",
          cvss: "4.3",
          type: "prion",
          is_exploit: "false",
          reference: "https://vulners.com/prion/PRION:CVE-2018-5743",
        },
        {
          id: "CVE-2020-8623",
          cvss: "4.3",
          type: "cve",
          is_exploit: "false",
          reference: "https://vulners.com/cve/CVE-2020-8623",
        },
        {
          id: "CVE-2020-8617",
          cvss: "4.3",
          type: "cve",
          is_exploit: "false",
          reference: "https://vulners.com/cve/CVE-2020-8617",
        },
        {
          id: "CVE-2019-6471",
          cvss: "4.3",
          type: "cve",
          is_exploit: "false",
          reference: "https://vulners.com/cve/CVE-2019-6471",
        },
        {
          id: "CVE-2019-6465",
          cvss: "4.3",
          type: "cve",
          is_exploit: "false",
          reference: "https://vulners.com/cve/CVE-2019-6465",
        },
        {
          id: "CVE-2018-5743",
          cvss: "4.3",
          type: "cve",
          is_exploit: "false",
          reference: "https://vulners.com/cve/CVE-2018-5743",
        },
        {
          id: "1337DAY-ID-34485",
          cvss: "4.3",
          type: "zdt",
          is_exploit: "true",
          reference: "https://vulners.com/zdt/1337DAY-ID-34485",
        },
        {
          id: "PRION:CVE-2021-25214",
          cvss: "4.0",
          type: "prion",
          is_exploit: "false",
          reference: "https://vulners.com/prion/PRION:CVE-2021-25214",
        },
        {
          id: "PRION:CVE-2020-8624",
          cvss: "4.0",
          type: "prion",
          is_exploit: "false",
          reference: "https://vulners.com/prion/PRION:CVE-2020-8624",
        },
        {
          id: "PRION:CVE-2020-8622",
          cvss: "4.0",
          type: "prion",
          is_exploit: "false",
          reference: "https://vulners.com/prion/PRION:CVE-2020-8622",
        },
        {
          id: "PRION:CVE-2018-5741",
          cvss: "4.0",
          type: "prion",
          is_exploit: "false",
          reference: "https://vulners.com/prion/PRION:CVE-2018-5741",
        },
        {
          id: "CVE-2021-25220",
          cvss: "4.0",
          type: "cve",
          is_exploit: "false",
          reference: "https://vulners.com/cve/CVE-2021-25220",
        },
        {
          id: "CVE-2021-25214",
          cvss: "4.0",
          type: "cve",
          is_exploit: "false",
          reference: "https://vulners.com/cve/CVE-2021-25214",
        },
        {
          id: "CVE-2020-8624",
          cvss: "4.0",
          type: "cve",
          is_exploit: "false",
          reference: "https://vulners.com/cve/CVE-2020-8624",
        },
        {
          id: "CVE-2020-8622",
          cvss: "4.0",
          type: "cve",
          is_exploit: "false",
          reference: "https://vulners.com/cve/CVE-2020-8622",
        },
        {
          id: "CVE-2018-5741",
          cvss: "4.0",
          type: "cve",
          is_exploit: "false",
          reference: "https://vulners.com/cve/CVE-2018-5741",
        },
        {
          id: "PRION:CVE-2018-5745",
          cvss: "3.5",
          type: "prion",
          is_exploit: "false",
          reference: "https://vulners.com/prion/PRION:CVE-2018-5745",
        },
        {
          id: "CVE-2018-5745",
          cvss: "3.5",
          type: "cve",
          is_exploit: "false",
          reference: "https://vulners.com/cve/CVE-2018-5745",
        },
        {
          id: "PRION:CVE-2021-25220",
          cvss: "3.3",
          type: "prion",
          is_exploit: "false",
          reference: "https://vulners.com/prion/PRION:CVE-2021-25220",
        },
        {
          id: "PRION:CVE-2020-8619",
          cvss: "3.3",
          type: "prion",
          is_exploit: "false",
          reference: "https://vulners.com/prion/PRION:CVE-2020-8619",
        },
        {
          id: "PRION:CVE-2020-8617",
          cvss: "2.6",
          type: "prion",
          is_exploit: "false",
          reference: "https://vulners.com/prion/PRION:CVE-2020-8617",
        },
      ],
    },
    {
      http: {
        request: {
          method: "GET",
          uri: "https://115.75.91.61",
        },
        response: {
          protocol: "HTTP/1.1",
          status_code: "200",
          status_reason: "OK",
          header_location: "",
          html_title: "",
        },
      },
      port: "80",
      service_name: "http",
      software: [
        {
          vendor: "nginx",
          product: "nginx",
          version: "",
        },
      ],
      vulnerabilities: [],
    },
    {
      http: {
        request: {
          method: "GET",
          uri: "https://115.75.91.61",
        },
        response: {
          protocol: "HTTP/1.1",
          status_code: "200",
          status_reason: "OK",
          header_location: "",
          html_title: "",
        },
      },
      port: "110",
      service_name: "pop3",
      software: [
        {
          vendor: "Dovecot pop3d",
          product: "Dovecot pop3d",
          version: "",
        },
      ],
      vulnerabilities: [],
    },
    {
      http: {
        request: {
          method: "GET",
          uri: "https://115.75.91.61",
        },
        response: {
          protocol: "HTTP/1.1",
          status_code: "200",
          status_reason: "OK",
          header_location: "",
          html_title: "",
        },
      },
      port: "143",
      service_name: "imap",
      software: [
        {
          vendor: "Dovecot imapd",
          product: "Dovecot imapd",
          version: "",
        },
      ],
      vulnerabilities: [],
    },
    {
      http: {
        request: {
          method: "GET",
          uri: "https://115.75.91.61",
        },
        response: {
          protocol: "HTTP/1.1",
          status_code: "200",
          status_reason: "OK",
          header_location: "",
          html_title: "",
        },
      },
      port: "443",
      service_name: "http",
      software: [
        {
          vendor: "nginx",
          product: "nginx",
          version: "",
        },
      ],
      vulnerabilities: [],
    },
    {
      http: {
        request: {
          method: "GET",
          uri: "https://115.75.91.61",
        },
        response: {
          protocol: "HTTP/1.1",
          status_code: "200",
          status_reason: "OK",
          header_location: "",
          html_title: "",
        },
      },
      port: "587",
      service_name: "smtp",
      software: [
        {
          vendor: "Exim smtpd",
          product: "Exim smtpd",
          version: "4.90_1",
        },
      ],
      vulnerabilities: [],
    },
    {
      http: {
        request: {
          method: "GET",
          uri: "https://115.75.91.61",
        },
        response: {
          protocol: "HTTP/1.1",
          status_code: "200",
          status_reason: "OK",
          header_location: "",
          html_title: "",
        },
      },
      port: "993",
      service_name: "imap",
      software: [
        {
          vendor: "Dovecot imapd",
          product: "Dovecot imapd",
          version: "",
        },
      ],
      vulnerabilities: [],
    },
    {
      http: {
        request: {
          method: "GET",
          uri: "https://115.75.91.61",
        },
        response: {
          protocol: "HTTP/1.1",
          status_code: "200",
          status_reason: "OK",
          header_location: "",
          html_title: "",
        },
      },
      port: "995",
      service_name: "pop3",
      software: [
        {
          vendor: "Dovecot pop3d",
          product: "Dovecot pop3d",
          version: "",
        },
      ],
      vulnerabilities: [],
    },
    {
      http: {
        request: {
          method: "GET",
          uri: "https://115.75.91.61",
        },
        response: {
          protocol: "HTTP/1.1",
          status_code: "200",
          status_reason: "OK",
          header_location: "",
          html_title: "",
        },
      },
      port: "2525",
      service_name: "smtp",
      software: [
        {
          vendor: "Exim smtpd",
          product: "Exim smtpd",
          version: "4.90_1",
        },
      ],
      vulnerabilities: [],
    },
    {
      http: {
        request: {
          method: "GET",
          uri: "https://115.75.91.61",
        },
        response: {
          protocol: "HTTP/1.1",
          status_code: "200",
          status_reason: "OK",
          header_location: "",
          html_title: "",
        },
      },
      port: "3306",
      service_name: "mysql",
      software: [
        {
          vendor: "MySQL",
          product: "MySQL",
          version: "5.7.41-0ubuntu0.18.04.1",
        },
      ],
      vulnerabilities: [
        {
          id: "PRION:CVE-2023-22084",
          cvss: "3.3",
          type: "prion",
          is_exploit: "false",
          reference: "https://vulners.com/prion/PRION:CVE-2023-22084",
        },
        {
          id: "PRION:CVE-2023-22028",
          cvss: "3.3",
          type: "prion",
          is_exploit: "false",
          reference: "https://vulners.com/prion/PRION:CVE-2023-22028",
        },
        {
          id: "PRION:CVE-2023-22026",
          cvss: "3.3",
          type: "prion",
          is_exploit: "false",
          reference: "https://vulners.com/prion/PRION:CVE-2023-22026",
        },
        {
          id: "PRION:CVE-2023-22015",
          cvss: "3.3",
          type: "prion",
          is_exploit: "false",
          reference: "https://vulners.com/prion/PRION:CVE-2023-22015",
        },
      ],
    },
    {
      http: {
        request: {
          method: "GET",
          uri: "https://115.75.91.61",
        },
        response: {
          protocol: "HTTP/1.1",
          status_code: "200",
          status_reason: "OK",
          header_location: "",
          html_title: "",
        },
      },
      port: "3389",
      service_name: "ms-wbt-server",
      software: [
        {
          vendor: "Microsoft Terminal Services",
          product: "Microsoft Terminal Services",
          version: "",
        },
      ],
      vulnerabilities: [],
    },
    {
      http: {
        request: {
          method: "GET",
          uri: "https://115.75.91.61",
        },
        response: {
          protocol: "HTTP/1.1",
          status_code: "200",
          status_reason: "OK",
          header_location: "",
          html_title: "",
        },
      },
      port: "8080",
      service_name: "http",
      software: [
        {
          vendor: "Apache httpd",
          product: "Apache httpd",
          version: "2.4.29",
        },
        {
          vendor: "mod_fcgid",
          product: "mod_fcgid",
          version: "2.3.9",
        },
        {
          vendor: "OpenSSL",
          product: "OpenSSL",
          version: "1.1.1g",
        },
      ],
      vulnerabilities: [
        {
          id: "CVE-2019-9517",
          cvss: "7.8",
          type: "cve",
          is_exploit: "false",
          reference: "https://vulners.com/cve/CVE-2019-9517",
        },
        {
          id: "PACKETSTORM:171631",
          cvss: "7.5",
          type: "packetstorm",
          is_exploit: "true",
          reference: "https://vulners.com/packetstorm/PACKETSTORM:171631",
        },
        {
          id: "EDB-ID:51193",
          cvss: "7.5",
          type: "exploitdb",
          is_exploit: "true",
          reference: "https://vulners.com/exploitdb/EDB-ID:51193",
        },
        {
          id: "CVE-2022-31813",
          cvss: "7.5",
          type: "cve",
          is_exploit: "false",
          reference: "https://vulners.com/cve/CVE-2022-31813",
        },
        {
          id: "CVE-2022-23943",
          cvss: "7.5",
          type: "cve",
          is_exploit: "false",
          reference: "https://vulners.com/cve/CVE-2022-23943",
        },
        {
          id: "CVE-2022-22720",
          cvss: "7.5",
          type: "cve",
          is_exploit: "false",
          reference: "https://vulners.com/cve/CVE-2022-22720",
        },
        {
          id: "CVE-2021-44790",
          cvss: "7.5",
          type: "cve",
          is_exploit: "false",
          reference: "https://vulners.com/cve/CVE-2021-44790",
        },
        {
          id: "CVE-2021-39275",
          cvss: "7.5",
          type: "cve",
          is_exploit: "false",
          reference: "https://vulners.com/cve/CVE-2021-39275",
        },
        {
          id: "CVE-2021-26691",
          cvss: "7.5",
          type: "cve",
          is_exploit: "false",
          reference: "https://vulners.com/cve/CVE-2021-26691",
        },
        {
          id: "CNVD-2022-73123",
          cvss: "7.5",
          type: "cnvd",
          is_exploit: "false",
          reference: "https://vulners.com/cnvd/CNVD-2022-73123",
        },
        {
          id: "CNVD-2022-03225",
          cvss: "7.5",
          type: "cnvd",
          is_exploit: "false",
          reference: "https://vulners.com/cnvd/CNVD-2022-03225",
        },
        {
          id: "CNVD-2021-102386",
          cvss: "7.5",
          type: "cnvd",
          is_exploit: "false",
          reference: "https://vulners.com/cnvd/CNVD-2021-102386",
        },
        {
          id: "1337DAY-ID-38427",
          cvss: "7.5",
          type: "zdt",
          is_exploit: "true",
          reference: "https://vulners.com/zdt/1337DAY-ID-38427",
        },
        {
          id: "EXPLOITPACK:44C5118F831D55FAF4259C41D8BDA0AB",
          cvss: "7.2",
          type: "exploitpack",
          is_exploit: "true",
          reference:
            "https://vulners.com/exploitpack/EXPLOITPACK:44C5118F831D55FAF4259C41D8BDA0AB",
        },
        {
          id: "EDB-ID:46676",
          cvss: "7.2",
          type: "exploitdb",
          is_exploit: "true",
          reference: "https://vulners.com/exploitdb/EDB-ID:46676",
        },
        {
          id: "CVE-2019-0211",
          cvss: "7.2",
          type: "cve",
          is_exploit: "false",
          reference: "https://vulners.com/cve/CVE-2019-0211",
        },
        {
          id: "1337DAY-ID-32502",
          cvss: "7.2",
          type: "zdt",
          is_exploit: "true",
          reference: "https://vulners.com/zdt/1337DAY-ID-32502",
        },
        {
          id: "FDF3DFA1-ED74-5EE2-BF5C-BA752CA34AE8",
          cvss: "6.8",
          type: "githubexploit",
          is_exploit: "true",
          reference:
            "https://vulners.com/githubexploit/FDF3DFA1-ED74-5EE2-BF5C-BA752CA34AE8",
        },
        {
          id: "CVE-2021-40438",
          cvss: "6.8",
          type: "cve",
          is_exploit: "false",
          reference: "https://vulners.com/cve/CVE-2021-40438",
        },
        {
          id: "CVE-2020-35452",
          cvss: "6.8",
          type: "cve",
          is_exploit: "false",
          reference: "https://vulners.com/cve/CVE-2020-35452",
        },
        {
          id: "CVE-2018-1312",
          cvss: "6.8",
          type: "cve",
          is_exploit: "false",
          reference: "https://vulners.com/cve/CVE-2018-1312",
        },
        {
          id: "CVE-2017-15715",
          cvss: "6.8",
          type: "cve",
          is_exploit: "false",
          reference: "https://vulners.com/cve/CVE-2017-15715",
        },
        {
          id: "CNVD-2022-03224",
          cvss: "6.8",
          type: "cnvd",
          is_exploit: "false",
          reference: "https://vulners.com/cnvd/CNVD-2022-03224",
        },
        {
          id: "8AFB43C5-ABD4-52AD-BB19-24D7884FF2A2",
          cvss: "6.8",
          type: "githubexploit",
          is_exploit: "true",
          reference:
            "https://vulners.com/githubexploit/8AFB43C5-ABD4-52AD-BB19-24D7884FF2A2",
        },
        {
          id: "4810E2D9-AC5F-5B08-BFB3-DDAFA2F63332",
          cvss: "6.8",
          type: "githubexploit",
          is_exploit: "true",
          reference:
            "https://vulners.com/githubexploit/4810E2D9-AC5F-5B08-BFB3-DDAFA2F63332",
        },
        {
          id: "4373C92A-2755-5538-9C91-0469C995AA9B",
          cvss: "6.8",
          type: "githubexploit",
          is_exploit: "true",
          reference:
            "https://vulners.com/githubexploit/4373C92A-2755-5538-9C91-0469C995AA9B",
        },
        {
          id: "0095E929-7573-5E4A-A7FA-F6598A35E8DE",
          cvss: "6.8",
          type: "githubexploit",
          is_exploit: "true",
          reference:
            "https://vulners.com/githubexploit/0095E929-7573-5E4A-A7FA-F6598A35E8DE",
        },
        {
          id: "OSV:BIT-2023-31122",
          cvss: "6.4",
          type: "osv",
          is_exploit: "false",
          reference: "https://vulners.com/osv/OSV:BIT-2023-31122",
        },
        {
          id: "CVE-2022-28615",
          cvss: "6.4",
          type: "cve",
          is_exploit: "false",
          reference: "https://vulners.com/cve/CVE-2022-28615",
        },
        {
          id: "CVE-2021-44224",
          cvss: "6.4",
          type: "cve",
          is_exploit: "false",
          reference: "https://vulners.com/cve/CVE-2021-44224",
        },
        {
          id: "CVE-2019-10082",
          cvss: "6.4",
          type: "cve",
          is_exploit: "false",
          reference: "https://vulners.com/cve/CVE-2019-10082",
        },
        {
          id: "CVE-2019-0217",
          cvss: "6.0",
          type: "cve",
          is_exploit: "false",
          reference: "https://vulners.com/cve/CVE-2019-0217",
        },
        {
          id: "CVE-2022-22721",
          cvss: "5.8",
          type: "cve",
          is_exploit: "false",
          reference: "https://vulners.com/cve/CVE-2022-22721",
        },
        {
          id: "CVE-2020-1927",
          cvss: "5.8",
          type: "cve",
          is_exploit: "false",
          reference: "https://vulners.com/cve/CVE-2020-1927",
        },
        {
          id: "CVE-2019-10098",
          cvss: "5.8",
          type: "cve",
          is_exploit: "false",
          reference: "https://vulners.com/cve/CVE-2019-10098",
        },
        {
          id: "1337DAY-ID-33577",
          cvss: "5.8",
          type: "zdt",
          is_exploit: "true",
          reference: "https://vulners.com/zdt/1337DAY-ID-33577",
        },
        {
          id: "CVE-2022-36760",
          cvss: "5.1",
          type: "cve",
          is_exploit: "false",
          reference: "https://vulners.com/cve/CVE-2022-36760",
        },
        {
          id: "OSV:BIT-2023-45802",
          cvss: "5.0",
          type: "osv",
          is_exploit: "false",
          reference: "https://vulners.com/osv/OSV:BIT-2023-45802",
        },
        {
          id: "OSV:BIT-2023-43622",
          cvss: "5.0",
          type: "osv",
          is_exploit: "false",
          reference: "https://vulners.com/osv/OSV:BIT-2023-43622",
        },
        {
          id: "F7F6E599-CEF4-5E03-8E10-FE18C4101E38",
          cvss: "5.0",
          type: "githubexploit",
          is_exploit: "true",
          reference:
            "https://vulners.com/githubexploit/F7F6E599-CEF4-5E03-8E10-FE18C4101E38",
        },
        {
          id: "E5C174E5-D6E8-56E0-8403-D287DE52EB3F",
          cvss: "5.0",
          type: "githubexploit",
          is_exploit: "true",
          reference:
            "https://vulners.com/githubexploit/E5C174E5-D6E8-56E0-8403-D287DE52EB3F",
        },
        {
          id: "DB6E1BBD-08B1-574D-A351-7D6BB9898A4A",
          cvss: "5.0",
          type: "githubexploit",
          is_exploit: "true",
          reference:
            "https://vulners.com/githubexploit/DB6E1BBD-08B1-574D-A351-7D6BB9898A4A",
        },
        {
          id: "CVE-2022-37436",
          cvss: "5.0",
          type: "cve",
          is_exploit: "false",
          reference: "https://vulners.com/cve/CVE-2022-37436",
        },
        {
          id: "CVE-2022-30556",
          cvss: "5.0",
          type: "cve",
          is_exploit: "false",
          reference: "https://vulners.com/cve/CVE-2022-30556",
        },
        {
          id: "CVE-2022-29404",
          cvss: "5.0",
          type: "cve",
          is_exploit: "false",
          reference: "https://vulners.com/cve/CVE-2022-29404",
        },
        {
          id: "CVE-2022-28614",
          cvss: "5.0",
          type: "cve",
          is_exploit: "false",
          reference: "https://vulners.com/cve/CVE-2022-28614",
        },
        {
          id: "CVE-2022-26377",
          cvss: "5.0",
          type: "cve",
          is_exploit: "false",
          reference: "https://vulners.com/cve/CVE-2022-26377",
        },
        {
          id: "CVE-2022-22719",
          cvss: "5.0",
          type: "cve",
          is_exploit: "false",
          reference: "https://vulners.com/cve/CVE-2022-22719",
        },
        {
          id: "CVE-2021-34798",
          cvss: "5.0",
          type: "cve",
          is_exploit: "false",
          reference: "https://vulners.com/cve/CVE-2021-34798",
        },
        {
          id: "CVE-2021-33193",
          cvss: "5.0",
          type: "cve",
          is_exploit: "false",
          reference: "https://vulners.com/cve/CVE-2021-33193",
        },
        {
          id: "CVE-2021-26690",
          cvss: "5.0",
          type: "cve",
          is_exploit: "false",
          reference: "https://vulners.com/cve/CVE-2021-26690",
        },
        {
          id: "CVE-2020-9490",
          cvss: "5.0",
          type: "cve",
          is_exploit: "false",
          reference: "https://vulners.com/cve/CVE-2020-9490",
        },
        {
          id: "CVE-2020-1934",
          cvss: "5.0",
          type: "cve",
          is_exploit: "false",
          reference: "https://vulners.com/cve/CVE-2020-1934",
        },
        {
          id: "CVE-2019-17567",
          cvss: "5.0",
          type: "cve",
          is_exploit: "false",
          reference: "https://vulners.com/cve/CVE-2019-17567",
        },
        {
          id: "CVE-2019-10081",
          cvss: "5.0",
          type: "cve",
          is_exploit: "false",
          reference: "https://vulners.com/cve/CVE-2019-10081",
        },
        {
          id: "CVE-2019-0220",
          cvss: "5.0",
          type: "cve",
          is_exploit: "false",
          reference: "https://vulners.com/cve/CVE-2019-0220",
        },
        {
          id: "CVE-2019-0196",
          cvss: "5.0",
          type: "cve",
          is_exploit: "false",
          reference: "https://vulners.com/cve/CVE-2019-0196",
        },
        {
          id: "CVE-2018-17199",
          cvss: "5.0",
          type: "cve",
          is_exploit: "false",
          reference: "https://vulners.com/cve/CVE-2018-17199",
        },
        {
          id: "CVE-2018-17189",
          cvss: "5.0",
          type: "cve",
          is_exploit: "false",
          reference: "https://vulners.com/cve/CVE-2018-17189",
        },
        {
          id: "CVE-2018-1333",
          cvss: "5.0",
          type: "cve",
          is_exploit: "false",
          reference: "https://vulners.com/cve/CVE-2018-1333",
        },
        {
          id: "CVE-2018-1303",
          cvss: "5.0",
          type: "cve",
          is_exploit: "false",
          reference: "https://vulners.com/cve/CVE-2018-1303",
        },
        {
          id: "CVE-2017-15710",
          cvss: "5.0",
          type: "cve",
          is_exploit: "false",
          reference: "https://vulners.com/cve/CVE-2017-15710",
        },
        {
          id: "CVE-2006-20001",
          cvss: "5.0",
          type: "cve",
          is_exploit: "false",
          reference: "https://vulners.com/cve/CVE-2006-20001",
        },
        {
          id: "CNVD-2023-93320",
          cvss: "5.0",
          type: "cnvd",
          is_exploit: "false",
          reference: "https://vulners.com/cnvd/CNVD-2023-93320",
        },
        {
          id: "CNVD-2023-80558",
          cvss: "5.0",
          type: "cnvd",
          is_exploit: "false",
          reference: "https://vulners.com/cnvd/CNVD-2023-80558",
        },
        {
          id: "CNVD-2022-73122",
          cvss: "5.0",
          type: "cnvd",
          is_exploit: "false",
          reference: "https://vulners.com/cnvd/CNVD-2022-73122",
        },
        {
          id: "CNVD-2022-53584",
          cvss: "5.0",
          type: "cnvd",
          is_exploit: "false",
          reference: "https://vulners.com/cnvd/CNVD-2022-53584",
        },
        {
          id: "CNVD-2022-53582",
          cvss: "5.0",
          type: "cnvd",
          is_exploit: "false",
          reference: "https://vulners.com/cnvd/CNVD-2022-53582",
        },
        {
          id: "CNVD-2022-03223",
          cvss: "5.0",
          type: "cnvd",
          is_exploit: "false",
          reference: "https://vulners.com/cnvd/CNVD-2022-03223",
        },
        {
          id: "C9A1C0C1-B6E3-5955-A4F1-DEA0E505B14B",
          cvss: "5.0",
          type: "githubexploit",
          is_exploit: "true",
          reference:
            "https://vulners.com/githubexploit/C9A1C0C1-B6E3-5955-A4F1-DEA0E505B14B",
        },
        {
          id: "BD3652A9-D066-57BA-9943-4E34970463B9",
          cvss: "5.0",
          type: "githubexploit",
          is_exploit: "true",
          reference:
            "https://vulners.com/githubexploit/BD3652A9-D066-57BA-9943-4E34970463B9",
        },
        {
          id: "B0208442-6E17-5772-B12D-B5BE30FA5540",
          cvss: "5.0",
          type: "githubexploit",
          is_exploit: "true",
          reference:
            "https://vulners.com/githubexploit/B0208442-6E17-5772-B12D-B5BE30FA5540",
        },
        {
          id: "A820A056-9F91-5059-B0BC-8D92C7A31A52",
          cvss: "5.0",
          type: "githubexploit",
          is_exploit: "true",
          reference:
            "https://vulners.com/githubexploit/A820A056-9F91-5059-B0BC-8D92C7A31A52",
        },
        {
          id: "9814661A-35A4-5DB7-BB25-A1040F365C81",
          cvss: "5.0",
          type: "githubexploit",
          is_exploit: "true",
          reference:
            "https://vulners.com/githubexploit/9814661A-35A4-5DB7-BB25-A1040F365C81",
        },
        {
          id: "17C6AD2A-8469-56C8-BBBE-1764D0DF1680",
          cvss: "5.0",
          type: "githubexploit",
          is_exploit: "true",
          reference:
            "https://vulners.com/githubexploit/17C6AD2A-8469-56C8-BBBE-1764D0DF1680",
        },
        {
          id: "CVE-2020-11993",
          cvss: "4.3",
          type: "cve",
          is_exploit: "false",
          reference: "https://vulners.com/cve/CVE-2020-11993",
        },
        {
          id: "CVE-2019-10092",
          cvss: "4.3",
          type: "cve",
          is_exploit: "false",
          reference: "https://vulners.com/cve/CVE-2019-10092",
        },
        {
          id: "CVE-2018-1302",
          cvss: "4.3",
          type: "cve",
          is_exploit: "false",
          reference: "https://vulners.com/cve/CVE-2018-1302",
        },
        {
          id: "CVE-2018-1301",
          cvss: "4.3",
          type: "cve",
          is_exploit: "false",
          reference: "https://vulners.com/cve/CVE-2018-1301",
        },
        {
          id: "CVE-2018-11763",
          cvss: "4.3",
          type: "cve",
          is_exploit: "false",
          reference: "https://vulners.com/cve/CVE-2018-11763",
        },
        {
          id: "4013EC74-B3C1-5D95-938A-54197A58586D",
          cvss: "4.3",
          type: "githubexploit",
          is_exploit: "true",
          reference:
            "https://vulners.com/githubexploit/4013EC74-B3C1-5D95-938A-54197A58586D",
        },
        {
          id: "1337DAY-ID-35422",
          cvss: "4.3",
          type: "zdt",
          is_exploit: "true",
          reference: "https://vulners.com/zdt/1337DAY-ID-35422",
        },
        {
          id: "1337DAY-ID-33575",
          cvss: "4.3",
          type: "zdt",
          is_exploit: "true",
          reference: "https://vulners.com/zdt/1337DAY-ID-33575",
        },
        {
          id: "CVE-2018-1283",
          cvss: "3.5",
          type: "cve",
          is_exploit: "false",
          reference: "https://vulners.com/cve/CVE-2018-1283",
        },
        {
          id: "PACKETSTORM:152441",
          cvss: "0.0",
          type: "packetstorm",
          is_exploit: "true",
          reference: "https://vulners.com/packetstorm/PACKETSTORM:152441",
        },
      ],
    },
    {
      http: {
        request: {
          method: "GET",
          uri: "https://115.75.91.61",
        },
        response: {
          protocol: "HTTP/1.1",
          status_code: "200",
          status_reason: "OK",
          header_location: "",
          html_title: "",
        },
      },
      port: "8443",
      service_name: "http",
      software: [
        {
          vendor: "Apache httpd",
          product: "Apache httpd",
          version: "2.4.29",
        },
        {
          vendor: "mod_fcgid",
          product: "mod_fcgid",
          version: "2.3.9",
        },
        {
          vendor: "OpenSSL",
          product: "OpenSSL",
          version: "1.1.1g",
        },
      ],
      vulnerabilities: [
        {
          id: "CVE-2019-9517",
          cvss: "7.8",
          type: "cve",
          is_exploit: "false",
          reference: "https://vulners.com/cve/CVE-2019-9517",
        },
        {
          id: "PACKETSTORM:171631",
          cvss: "7.5",
          type: "packetstorm",
          is_exploit: "true",
          reference: "https://vulners.com/packetstorm/PACKETSTORM:171631",
        },
        {
          id: "EDB-ID:51193",
          cvss: "7.5",
          type: "exploitdb",
          is_exploit: "true",
          reference: "https://vulners.com/exploitdb/EDB-ID:51193",
        },
        {
          id: "CVE-2022-31813",
          cvss: "7.5",
          type: "cve",
          is_exploit: "false",
          reference: "https://vulners.com/cve/CVE-2022-31813",
        },
        {
          id: "CVE-2022-23943",
          cvss: "7.5",
          type: "cve",
          is_exploit: "false",
          reference: "https://vulners.com/cve/CVE-2022-23943",
        },
        {
          id: "CVE-2022-22720",
          cvss: "7.5",
          type: "cve",
          is_exploit: "false",
          reference: "https://vulners.com/cve/CVE-2022-22720",
        },
        {
          id: "CVE-2021-44790",
          cvss: "7.5",
          type: "cve",
          is_exploit: "false",
          reference: "https://vulners.com/cve/CVE-2021-44790",
        },
        {
          id: "CVE-2021-39275",
          cvss: "7.5",
          type: "cve",
          is_exploit: "false",
          reference: "https://vulners.com/cve/CVE-2021-39275",
        },
        {
          id: "CVE-2021-26691",
          cvss: "7.5",
          type: "cve",
          is_exploit: "false",
          reference: "https://vulners.com/cve/CVE-2021-26691",
        },
        {
          id: "CNVD-2022-73123",
          cvss: "7.5",
          type: "cnvd",
          is_exploit: "false",
          reference: "https://vulners.com/cnvd/CNVD-2022-73123",
        },
        {
          id: "CNVD-2022-03225",
          cvss: "7.5",
          type: "cnvd",
          is_exploit: "false",
          reference: "https://vulners.com/cnvd/CNVD-2022-03225",
        },
        {
          id: "CNVD-2021-102386",
          cvss: "7.5",
          type: "cnvd",
          is_exploit: "false",
          reference: "https://vulners.com/cnvd/CNVD-2021-102386",
        },
        {
          id: "1337DAY-ID-38427",
          cvss: "7.5",
          type: "zdt",
          is_exploit: "true",
          reference: "https://vulners.com/zdt/1337DAY-ID-38427",
        },
        {
          id: "EXPLOITPACK:44C5118F831D55FAF4259C41D8BDA0AB",
          cvss: "7.2",
          type: "exploitpack",
          is_exploit: "true",
          reference:
            "https://vulners.com/exploitpack/EXPLOITPACK:44C5118F831D55FAF4259C41D8BDA0AB",
        },
        {
          id: "EDB-ID:46676",
          cvss: "7.2",
          type: "exploitdb",
          is_exploit: "true",
          reference: "https://vulners.com/exploitdb/EDB-ID:46676",
        },
        {
          id: "CVE-2019-0211",
          cvss: "7.2",
          type: "cve",
          is_exploit: "false",
          reference: "https://vulners.com/cve/CVE-2019-0211",
        },
        {
          id: "1337DAY-ID-32502",
          cvss: "7.2",
          type: "zdt",
          is_exploit: "true",
          reference: "https://vulners.com/zdt/1337DAY-ID-32502",
        },
        {
          id: "FDF3DFA1-ED74-5EE2-BF5C-BA752CA34AE8",
          cvss: "6.8",
          type: "githubexploit",
          is_exploit: "true",
          reference:
            "https://vulners.com/githubexploit/FDF3DFA1-ED74-5EE2-BF5C-BA752CA34AE8",
        },
        {
          id: "CVE-2021-40438",
          cvss: "6.8",
          type: "cve",
          is_exploit: "false",
          reference: "https://vulners.com/cve/CVE-2021-40438",
        },
        {
          id: "CVE-2020-35452",
          cvss: "6.8",
          type: "cve",
          is_exploit: "false",
          reference: "https://vulners.com/cve/CVE-2020-35452",
        },
        {
          id: "CVE-2018-1312",
          cvss: "6.8",
          type: "cve",
          is_exploit: "false",
          reference: "https://vulners.com/cve/CVE-2018-1312",
        },
        {
          id: "CVE-2017-15715",
          cvss: "6.8",
          type: "cve",
          is_exploit: "false",
          reference: "https://vulners.com/cve/CVE-2017-15715",
        },
        {
          id: "CNVD-2022-03224",
          cvss: "6.8",
          type: "cnvd",
          is_exploit: "false",
          reference: "https://vulners.com/cnvd/CNVD-2022-03224",
        },
        {
          id: "8AFB43C5-ABD4-52AD-BB19-24D7884FF2A2",
          cvss: "6.8",
          type: "githubexploit",
          is_exploit: "true",
          reference:
            "https://vulners.com/githubexploit/8AFB43C5-ABD4-52AD-BB19-24D7884FF2A2",
        },
        {
          id: "4810E2D9-AC5F-5B08-BFB3-DDAFA2F63332",
          cvss: "6.8",
          type: "githubexploit",
          is_exploit: "true",
          reference:
            "https://vulners.com/githubexploit/4810E2D9-AC5F-5B08-BFB3-DDAFA2F63332",
        },
        {
          id: "4373C92A-2755-5538-9C91-0469C995AA9B",
          cvss: "6.8",
          type: "githubexploit",
          is_exploit: "true",
          reference:
            "https://vulners.com/githubexploit/4373C92A-2755-5538-9C91-0469C995AA9B",
        },
        {
          id: "0095E929-7573-5E4A-A7FA-F6598A35E8DE",
          cvss: "6.8",
          type: "githubexploit",
          is_exploit: "true",
          reference:
            "https://vulners.com/githubexploit/0095E929-7573-5E4A-A7FA-F6598A35E8DE",
        },
        {
          id: "OSV:BIT-2023-31122",
          cvss: "6.4",
          type: "osv",
          is_exploit: "false",
          reference: "https://vulners.com/osv/OSV:BIT-2023-31122",
        },
        {
          id: "CVE-2022-28615",
          cvss: "6.4",
          type: "cve",
          is_exploit: "false",
          reference: "https://vulners.com/cve/CVE-2022-28615",
        },
        {
          id: "CVE-2021-44224",
          cvss: "6.4",
          type: "cve",
          is_exploit: "false",
          reference: "https://vulners.com/cve/CVE-2021-44224",
        },
        {
          id: "CVE-2019-10082",
          cvss: "6.4",
          type: "cve",
          is_exploit: "false",
          reference: "https://vulners.com/cve/CVE-2019-10082",
        },
        {
          id: "CVE-2019-0217",
          cvss: "6.0",
          type: "cve",
          is_exploit: "false",
          reference: "https://vulners.com/cve/CVE-2019-0217",
        },
        {
          id: "CVE-2022-22721",
          cvss: "5.8",
          type: "cve",
          is_exploit: "false",
          reference: "https://vulners.com/cve/CVE-2022-22721",
        },
        {
          id: "CVE-2020-1927",
          cvss: "5.8",
          type: "cve",
          is_exploit: "false",
          reference: "https://vulners.com/cve/CVE-2020-1927",
        },
        {
          id: "CVE-2019-10098",
          cvss: "5.8",
          type: "cve",
          is_exploit: "false",
          reference: "https://vulners.com/cve/CVE-2019-10098",
        },
        {
          id: "1337DAY-ID-33577",
          cvss: "5.8",
          type: "zdt",
          is_exploit: "true",
          reference: "https://vulners.com/zdt/1337DAY-ID-33577",
        },
        {
          id: "CVE-2022-36760",
          cvss: "5.1",
          type: "cve",
          is_exploit: "false",
          reference: "https://vulners.com/cve/CVE-2022-36760",
        },
        {
          id: "OSV:BIT-2023-45802",
          cvss: "5.0",
          type: "osv",
          is_exploit: "false",
          reference: "https://vulners.com/osv/OSV:BIT-2023-45802",
        },
        {
          id: "OSV:BIT-2023-43622",
          cvss: "5.0",
          type: "osv",
          is_exploit: "false",
          reference: "https://vulners.com/osv/OSV:BIT-2023-43622",
        },
        {
          id: "F7F6E599-CEF4-5E03-8E10-FE18C4101E38",
          cvss: "5.0",
          type: "githubexploit",
          is_exploit: "true",
          reference:
            "https://vulners.com/githubexploit/F7F6E599-CEF4-5E03-8E10-FE18C4101E38",
        },
        {
          id: "E5C174E5-D6E8-56E0-8403-D287DE52EB3F",
          cvss: "5.0",
          type: "githubexploit",
          is_exploit: "true",
          reference:
            "https://vulners.com/githubexploit/E5C174E5-D6E8-56E0-8403-D287DE52EB3F",
        },
        {
          id: "DB6E1BBD-08B1-574D-A351-7D6BB9898A4A",
          cvss: "5.0",
          type: "githubexploit",
          is_exploit: "true",
          reference:
            "https://vulners.com/githubexploit/DB6E1BBD-08B1-574D-A351-7D6BB9898A4A",
        },
        {
          id: "CVE-2022-37436",
          cvss: "5.0",
          type: "cve",
          is_exploit: "false",
          reference: "https://vulners.com/cve/CVE-2022-37436",
        },
        {
          id: "CVE-2022-30556",
          cvss: "5.0",
          type: "cve",
          is_exploit: "false",
          reference: "https://vulners.com/cve/CVE-2022-30556",
        },
        {
          id: "CVE-2022-29404",
          cvss: "5.0",
          type: "cve",
          is_exploit: "false",
          reference: "https://vulners.com/cve/CVE-2022-29404",
        },
        {
          id: "CVE-2022-28614",
          cvss: "5.0",
          type: "cve",
          is_exploit: "false",
          reference: "https://vulners.com/cve/CVE-2022-28614",
        },
        {
          id: "CVE-2022-26377",
          cvss: "5.0",
          type: "cve",
          is_exploit: "false",
          reference: "https://vulners.com/cve/CVE-2022-26377",
        },
        {
          id: "CVE-2022-22719",
          cvss: "5.0",
          type: "cve",
          is_exploit: "false",
          reference: "https://vulners.com/cve/CVE-2022-22719",
        },
        {
          id: "CVE-2021-34798",
          cvss: "5.0",
          type: "cve",
          is_exploit: "false",
          reference: "https://vulners.com/cve/CVE-2021-34798",
        },
        {
          id: "CVE-2021-33193",
          cvss: "5.0",
          type: "cve",
          is_exploit: "false",
          reference: "https://vulners.com/cve/CVE-2021-33193",
        },
        {
          id: "CVE-2021-26690",
          cvss: "5.0",
          type: "cve",
          is_exploit: "false",
          reference: "https://vulners.com/cve/CVE-2021-26690",
        },
        {
          id: "CVE-2020-9490",
          cvss: "5.0",
          type: "cve",
          is_exploit: "false",
          reference: "https://vulners.com/cve/CVE-2020-9490",
        },
        {
          id: "CVE-2020-1934",
          cvss: "5.0",
          type: "cve",
          is_exploit: "false",
          reference: "https://vulners.com/cve/CVE-2020-1934",
        },
        {
          id: "CVE-2019-17567",
          cvss: "5.0",
          type: "cve",
          is_exploit: "false",
          reference: "https://vulners.com/cve/CVE-2019-17567",
        },
        {
          id: "CVE-2019-10081",
          cvss: "5.0",
          type: "cve",
          is_exploit: "false",
          reference: "https://vulners.com/cve/CVE-2019-10081",
        },
        {
          id: "CVE-2019-0220",
          cvss: "5.0",
          type: "cve",
          is_exploit: "false",
          reference: "https://vulners.com/cve/CVE-2019-0220",
        },
        {
          id: "CVE-2019-0196",
          cvss: "5.0",
          type: "cve",
          is_exploit: "false",
          reference: "https://vulners.com/cve/CVE-2019-0196",
        },
        {
          id: "CVE-2018-17199",
          cvss: "5.0",
          type: "cve",
          is_exploit: "false",
          reference: "https://vulners.com/cve/CVE-2018-17199",
        },
        {
          id: "CVE-2018-17189",
          cvss: "5.0",
          type: "cve",
          is_exploit: "false",
          reference: "https://vulners.com/cve/CVE-2018-17189",
        },
        {
          id: "CVE-2018-1333",
          cvss: "5.0",
          type: "cve",
          is_exploit: "false",
          reference: "https://vulners.com/cve/CVE-2018-1333",
        },
        {
          id: "CVE-2018-1303",
          cvss: "5.0",
          type: "cve",
          is_exploit: "false",
          reference: "https://vulners.com/cve/CVE-2018-1303",
        },
        {
          id: "CVE-2017-15710",
          cvss: "5.0",
          type: "cve",
          is_exploit: "false",
          reference: "https://vulners.com/cve/CVE-2017-15710",
        },
        {
          id: "CVE-2006-20001",
          cvss: "5.0",
          type: "cve",
          is_exploit: "false",
          reference: "https://vulners.com/cve/CVE-2006-20001",
        },
        {
          id: "CNVD-2023-93320",
          cvss: "5.0",
          type: "cnvd",
          is_exploit: "false",
          reference: "https://vulners.com/cnvd/CNVD-2023-93320",
        },
        {
          id: "CNVD-2023-80558",
          cvss: "5.0",
          type: "cnvd",
          is_exploit: "false",
          reference: "https://vulners.com/cnvd/CNVD-2023-80558",
        },
        {
          id: "CNVD-2022-73122",
          cvss: "5.0",
          type: "cnvd",
          is_exploit: "false",
          reference: "https://vulners.com/cnvd/CNVD-2022-73122",
        },
        {
          id: "CNVD-2022-53584",
          cvss: "5.0",
          type: "cnvd",
          is_exploit: "false",
          reference: "https://vulners.com/cnvd/CNVD-2022-53584",
        },
        {
          id: "CNVD-2022-53582",
          cvss: "5.0",
          type: "cnvd",
          is_exploit: "false",
          reference: "https://vulners.com/cnvd/CNVD-2022-53582",
        },
        {
          id: "CNVD-2022-03223",
          cvss: "5.0",
          type: "cnvd",
          is_exploit: "false",
          reference: "https://vulners.com/cnvd/CNVD-2022-03223",
        },
        {
          id: "C9A1C0C1-B6E3-5955-A4F1-DEA0E505B14B",
          cvss: "5.0",
          type: "githubexploit",
          is_exploit: "true",
          reference:
            "https://vulners.com/githubexploit/C9A1C0C1-B6E3-5955-A4F1-DEA0E505B14B",
        },
        {
          id: "BD3652A9-D066-57BA-9943-4E34970463B9",
          cvss: "5.0",
          type: "githubexploit",
          is_exploit: "true",
          reference:
            "https://vulners.com/githubexploit/BD3652A9-D066-57BA-9943-4E34970463B9",
        },
        {
          id: "B0208442-6E17-5772-B12D-B5BE30FA5540",
          cvss: "5.0",
          type: "githubexploit",
          is_exploit: "true",
          reference:
            "https://vulners.com/githubexploit/B0208442-6E17-5772-B12D-B5BE30FA5540",
        },
        {
          id: "A820A056-9F91-5059-B0BC-8D92C7A31A52",
          cvss: "5.0",
          type: "githubexploit",
          is_exploit: "true",
          reference:
            "https://vulners.com/githubexploit/A820A056-9F91-5059-B0BC-8D92C7A31A52",
        },
        {
          id: "9814661A-35A4-5DB7-BB25-A1040F365C81",
          cvss: "5.0",
          type: "githubexploit",
          is_exploit: "true",
          reference:
            "https://vulners.com/githubexploit/9814661A-35A4-5DB7-BB25-A1040F365C81",
        },
        {
          id: "17C6AD2A-8469-56C8-BBBE-1764D0DF1680",
          cvss: "5.0",
          type: "githubexploit",
          is_exploit: "true",
          reference:
            "https://vulners.com/githubexploit/17C6AD2A-8469-56C8-BBBE-1764D0DF1680",
        },
        {
          id: "CVE-2020-11993",
          cvss: "4.3",
          type: "cve",
          is_exploit: "false",
          reference: "https://vulners.com/cve/CVE-2020-11993",
        },
        {
          id: "CVE-2019-10092",
          cvss: "4.3",
          type: "cve",
          is_exploit: "false",
          reference: "https://vulners.com/cve/CVE-2019-10092",
        },
        {
          id: "CVE-2018-1302",
          cvss: "4.3",
          type: "cve",
          is_exploit: "false",
          reference: "https://vulners.com/cve/CVE-2018-1302",
        },
        {
          id: "CVE-2018-1301",
          cvss: "4.3",
          type: "cve",
          is_exploit: "false",
          reference: "https://vulners.com/cve/CVE-2018-1301",
        },
        {
          id: "CVE-2018-11763",
          cvss: "4.3",
          type: "cve",
          is_exploit: "false",
          reference: "https://vulners.com/cve/CVE-2018-11763",
        },
        {
          id: "4013EC74-B3C1-5D95-938A-54197A58586D",
          cvss: "4.3",
          type: "githubexploit",
          is_exploit: "true",
          reference:
            "https://vulners.com/githubexploit/4013EC74-B3C1-5D95-938A-54197A58586D",
        },
        {
          id: "1337DAY-ID-35422",
          cvss: "4.3",
          type: "zdt",
          is_exploit: "true",
          reference: "https://vulners.com/zdt/1337DAY-ID-35422",
        },
        {
          id: "1337DAY-ID-33575",
          cvss: "4.3",
          type: "zdt",
          is_exploit: "true",
          reference: "https://vulners.com/zdt/1337DAY-ID-33575",
        },
        {
          id: "CVE-2018-1283",
          cvss: "3.5",
          type: "cve",
          is_exploit: "false",
          reference: "https://vulners.com/cve/CVE-2018-1283",
        },
        {
          id: "PACKETSTORM:152441",
          cvss: "0.0",
          type: "packetstorm",
          is_exploit: "true",
          reference: "https://vulners.com/packetstorm/PACKETSTORM:152441",
        },
      ],
    },
  ],
  ssl: [],
  autonomous_system: {
    asn: "AS7552",
    description: "MAINT-VN-VNNIC",
    bgp_prefix: "115.72.0.0/13",
    name: "VIETTEL-VN",
    country_code: "VN",
  },
  operating_system: {
    vendor: "",
    product: "",
  },
  dns: [
    {
      Asset_Name: "antoanthucpham.angiang.gov.vn.",
      Record_type: "A",
      Record: "115.75.91.61",
    },
    {
      Asset_Name: "antoanthucpham.angiang.gov.vn.",
      Record_type: "AAAA",
      Record: "2402:800:63b4:b1c2:215:5dff:fe02:302",
    },
  ],
};

const CVEData = (service) => {
  return data.services.find((item) => item.service_name === service);
}

const serviceData = data.services;

const dataCVE = data.services.filter((services) => services.vulnerabilities.length > 0)

export { data, dataCVE, CVEData, serviceData};
